SYSTEM_ERROR_CODES = {
    "JOB_NOT_FOUND",
    "PROFILE_NOT_FOUND",
    "INVALID_IMAGE",
    "UNSUPPORTED_FORMAT",
    "IMAGE_CORRUPTED",
    "STORAGE_FAILED",
    "DATABASE_FAILED",
    "QUEUE_FAILED",
    "INFERENCE_FAILED",
    "PROCESSING_TIMEOUT",
    "CALLBACK_FAILED",
}
